create table if not exists public.schedule_job_ref_links (
  id bigint generated by default as identity primary key,
  schedule_assignment_id uuid not null references public.schedule_assignments(id) on delete cascade,
  job_planning_entry_id bigint not null references public.job_planning_entries(id) on delete cascade,
  job_ref text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint schedule_job_ref_links_job_planning_entry_id_key unique (job_planning_entry_id)
);

create index if not exists idx_schedule_job_ref_links_assignment_id
  on public.schedule_job_ref_links (schedule_assignment_id);

create index if not exists idx_schedule_job_ref_links_job_planning_entry_id
  on public.schedule_job_ref_links (job_planning_entry_id);

grant select, insert, update, delete on table public.schedule_job_ref_links to authenticated;
grant all privileges on table public.schedule_job_ref_links to service_role;
grant usage, select on all sequences in schema public to authenticated;
grant all privileges on all sequences in schema public to service_role;
